# Generated by Django 4.2.9 on 2024-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dec',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
